[package]
name = "rotz"
version = "0.9.0"
edition = "2021"
authors = ["Paul Volavsek <paul.volavsek@gmail.com>"]
license = "MIT"
description = "Fully cross platform dotfile manager written in rust."
repository = "https://github.com/volllly/rotz"
readme = "./README.md"
documentation = "https://docs.rs/rotz/"
keywords = ["dotfiles", "dotfiles-manager", "dotfile-manager", "cross-platform"]
categories = ["command-line-utilities"]

[features]

default = ["yaml"]
yaml = ["serde_yaml", "figment/yaml"]
toml = ["serde_toml", "figment/toml"]
json = ["serde_json", "figment/json"]

[dependencies]
clap = { version = "4.0.12", features = ["derive", "color"] }
serde_yaml = { version = "0.9.13", optional = true }
serde_toml = { package = "toml", version = "0.5.9", optional = true }
serde_json = { version = "1.0.86", optional = true }
figment = { version = "0.10.8", default-features = false, features = ["env"] }
directories = "4.0.1"
once_cell = "1.15.0"
derive_more = "0.99.17"
serde = { version = "1.0.145", features = ["derive"] }
crossterm = "0.25.0"
itertools = "0.10.5"
thiserror = "1.0.37"
miette = { version = "5.3.0", features = ["fancy"] }
baker = "0.1.2"
indexmap = "1.9.1"
handlebars = "4.3.5"
handlebars_misc_helpers = { version = "0.12.1" }
shellwords = "1.1.0"
path-absolutize = "3.0.13"
walkdir = "2.3.2"
wax = { version = "0.5.0", features = ["miette"] }
whoami = "1.2.3"
path-slash = "0.2.1"
velcro = "0.5.3"
tap = "1.0.1"

[target.'cfg(windows)'.dependencies]
junction = "0.2.0"

[dev-dependencies]
fake = { version = "2.5.0", features = ["derive"] }
rand = "0.8.5"
rstest = "0.15.0"
speculoos = "0.9.0"

[profile.dev]
opt-level = 0
