[package]
name = "rotz"
version = "0.3.2"
edition = "2021"
authors = [ "Paul Volavsek <paul.volavsek@gmail.com>" ]
license = "MIT"
description = "Fully cross platform dotfile manager written in rust."
repository = "https://github.com/volllly/rotz"
readme = "./README.md"
documentation = "https://docs.rs/rotz/"
keywords = [ "dotfiles", "dotfile", "manager", "dotfile-manager", "cross-platform" ]
categories = [ "command-line-utilities" ]

[features]

default = [ "yaml" ]
yaml = [ "serde_yaml", "figment/yaml" ]
toml = [ "serde_toml", "figment/toml" ]
json = [ "figment/json" ]

[dependencies]
clap = { version = "3.1.16", features = [ "derive" ] }
serde_yaml = { version = "0.8.24", optional = true }
serde_toml = { package = "toml", version = "0.5.9", optional = true }
serde_json = "1.0.81"
figment = { version = "0.10.6", default-features = false, features = [ "env" ] }
directories = "4.0.1"
once_cell = "1.10.0"
derive_more = "0.99.17"
serde = { version = "1.0.137", features = [ "derive" ] }
crossterm = "0.23.2"
itertools = "0.10.3"
thiserror = "1.0.31"
somok = "1.5.0"
miette = { version = "5.1.0", features = [ "fancy" ] }
baker = "0.1.2"
indexmap = "1.8.2"
handlebars = "4.3.1"
handlebars_misc_helpers = { version = "0.12.1" }
shellwords = "1.1.0"

[target.'cfg(windows)'.dependencies]
junction = "0.2.0"

[dev-dependencies]
fake = { version = "2.4.3", features = [ "derive" ] }
rand = "0.8.5"
rstest = "0.15.0"
speculoos = "0.9.0"
