remote_theme: pmarsceill/just-the-docs

title: Rotz 👃

aux_links:
  <img height="32" width="32" src="https://unpkg.com/simple-icons@v6/icons/github.svg" />:
    - //github.com/volllly/rotz
  <img src="https://img.shields.io/crates/v/rotz">:
    - //crates.io/crates/rotz

aux_links_new_tab: true