remote_theme: pmarsceill/just-the-docs

title: Rotz 👃

aux_links:
  <img height="20" width="20" src="https://unpkg.com/simple-icons@v6/icons/github.svg" />: [ //github.com/volllly/rotz ]
  <img src="https://img.shields.io/crates/v/rotz">: [ //crates.io/crates/rotz ]

aux_links_new_tab: true